### PR TITLE
Added Laravel 5.4 compatibility

### PR DESCRIPTION
**Pull request by rene-vorndran**
-compatiblity to Laravel 5.4
-fixed same rule translation

### CODE REVIEW

**Comment by bgultekin** [comment]
As I understand from composer.json, you dismissed backward compability. That's why I should reject. If you considered backward compability and sent pull request again, I would happily accept.

Also, you can't change name and email information in composer.json for this repo. Of course you can do whatever you want, in your fork.

**Comment by rene-vorndran** [comment]
The FormBuilder constructor changed and does now require a view parameter, thats why i changed the composer requirement. If you put my changes into a new branch (in my fork i used 1.2) composer will only load this version if "laravelcollective/html" in Version 5.4 o higher is used, so it will not break the installation for all the users that use earlier versions. 

If i remove the name from composer.json will you then accept?

**Comment by bgultekin** [comment]
After short test, sure I will. BTW, Sorry for late reply, I couldn't find time to maintain repo. That's why I added two collaborators to repo, I think they are in same situation, too. If you think to use this package in a continuous project and you want, you can become a collaborator.

**Comment by phpspider** [comment]
What's the reason you are adding  \Illuminate\View\Factory $view in between existing parameters.
public function __construct(\Collective\Html\HtmlBuilder $html, \Illuminate\Routing\UrlGenerator $url, \Illuminate\View\Factory $view, $csrfToken, Converter\Base\Converter $converter)

This can be added as last parametrs. Isn't it ?

Thanks for the contribution.

**Comment by r-springmann** [comment]
Because the class this is based on has changed its constructor to this Syntax [https://github.com/LaravelCollective/html/blob/5.4/src/FormBuilder.php](https://github.com/LaravelCollective/html/blob/5.4/src/FormBuilder.php)

**Comment by rene-vorndran** [comment]
I removed the name in composer.json. What would i have to do if a would become a colaborator? Check pull requests and maintain the project?

**Comment by bgultekin** [comment]
Yes, that's all. Of course, if you want you can write some unit tests to make it easier.

**Pull request merged**
