### PR TITLE
Update README document for the new improvements

### PR DESCRIPTION
**Pull request by nthachus**
Please don't forget to update the distribution url for composer package https://packagist.org/packages/bllim/laravalid#dev-laravel4 :-)

### CODE REVIEW

**Comment by bgultekin** [comment]
What you mean with distribution url? You mean composer json sample in README.ME file?

**Comment by nthachus** [comment]
No, I mean the `packagist` package: https://packagist.org/packages/bllim/laravalid
It doesn't show the latest code on the Github, bro :-)
So, we need to update info for that, right?

**Comment by bgultekin** [comment]
Hmm sorry, packagist was updating automatically but it didn't work this time :). Anyway, I updated it, you can check. Thanks for contribution 👍 .

**Comment by nthachus** [comment]
Yeah, it was updated, thank you.
:-)

**Pull request merged**
